version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  checkout-source:
    executor: aws-cli/default
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  pip-install-test:
    docker:
      - image: 'python:3.7'
    steps:
#       - attach_workspace:
#           at: .    
      - run: pip install pandas==1.1.4 
      - run: ls -al
  yum-install-test:
    docker:
      - image: 'amazonlinux:latest'
    steps:
      - run: yum install -y tar gzip
      - attach_workspace:
          at: .
      - run: yum install -y httpd
  docstring-test:
    docker:
      - image: 'python:3.7'
    steps:
      - attach_workspace:
          at: .    
      - run:
          name: 'Run Doctest through Pytest'
          command: |
            pip install docstring==0.1.2.4
            pip install pytest==6.1.2
            pytest --doctest-modules
  black-test:
    docker:
      - image: 'python:3.7'
    steps:
      - attach_workspace:
          at: .    
      - run:
          name: 'Run a code style check through Black'
          command: |
            pip install black==20.8b1
            python -m black .
  remove-magic-commands:
    docker:
      - image: 'python:3.7'
    steps:
      - attach_workspace:
          at: .    
      - run: python -c "print(2+3)"
      - persist_to_workspace:
          root: .
          paths:
            - .      
  prepare-configuration-files:
    docker:
      - image: 'alpine:latest'
    steps:
      - attach_workspace:
          at: .    
      - run: echo "Please define any commands to masage files ..."
      - persist_to_workspace:
          root: .
          paths:
            - .      
  deploy:
    executor: aws-cli/default
    environment:
      S3_LOCATION: 's3://jeonl-circleci-sec-test'
    steps:
      # Mount a workspace
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload the file into S3 bucket
          command: aws s3 cp notebook_test.nbconvert.ipynb ${S3_LOCATION}
workflows:
  general-workflow:
    jobs:
      - checkout-source
      - pip-install-test:
          requires:
            - checkout-source
      - yum-install-test:
          requires:
            - checkout-source
      - docstring-test:
          requires:
            - pip-install-test
            - yum-install-test
          filters:
            branches:
              only:
                - /(feature|defect)[/].*/            
      - black-test:
          requires:
            - pip-install-test
            - yum-install-test         
          filters:
            branches:
              only:
                - /(feature|defect)[/].*/            
      - remove-magic-commands:
          requires:
            - pip-install-test
            - yum-install-test
      - prepare-configuration-files:
          requires:
            - pip-install-test
            - yum-install-test
      - deploy:
          requires:
            - remove-magic-commands
            - prepare-configuration-files
          filters:
            branches:
              only: master
          context:
            - aws-context
