#!/bin/bash

branch_name=$(git rev-parse --abbrev-ref HEAD)

if [[ "$branch_name" =~ "master" ]]; then
  echo "Not allowed to push directly into master branch ..."
  exit 1
elif [[ "$branch_name" =~ ^(feature|defect)/MFAS-[0-9]*-.*$ ]]; then
  exit 0
else
  echo "Not valid branch name convention ..."
  exit 1
fi
